#pragma once
int quantity_of_bicycles();
struct bicycle* catalog;
struct bicycle* memory_catalog(int* n);
void enter_mas_structure(int n, struct bicycle* mas);
void show_cat(struct bicycle const* mas, int* n);
void del_struct(struct bicycle* mas, int* n);
void sort_1_field(struct bicycle* mas, int* n);
void sort_2_field(struct bicycle* mas, int* n);
void check_choice_task(int* ch);
void check_go_choice(int* ch);
void checker(struct bicycle* mas, int i, int k);
void check_choice_sort(int* ch);
void check_del_str(int* x, int n);
void del(struct bicycle** mas, int x, int* n);
void sort_1_field(struct bicycle* mas, int* n);
void check_2_choices_sort(int ch_1, int* ch_2);
int text_check(char* mas_1, char const* mas_2);
int int_check(int a, int b);
int variants(int ch_1, int flag, struct bicycle* mas);
void free_struct(int n, struct bicycle** mas);
void sort_2(struct bicycle* mas, int n, int ch_1, int ch_2);
void sort_1(struct bicycle* mas, int n, int ch_1);